/*
 * ============================================================================
 *  Vault RE (MRI) listings client.
 *
 *  Docs: https://docs.api.vaultre.com.au/
 *
 *  AUTH — two headers are required on every request:
 *    X-Api-Key:     <integrator API key>     ← VAULT_API_KEY   (provisioned by MRI)
 *    Authorization: Bearer <access token>    ← VAULT_ACCESS_TOKEN
 *  The API key ALONE returns 401. The per-office Access Token is generated by the
 *  office inside VaultRE (Office Integrations → Third-Party Access → Create Token)
 *  and handed to us. Both live in the repo-root .env; neither reaches the browser.
 *
 *  RATE LIMIT: 10 req/s, 10,000/day. The docs explicitly say DO NOT call the API
 *  live on every page load — sync periodically and cache. We cache in-memory with
 *  a TTL and only refetch on expiry.
 *
 *  PHOTOS: hotlinking Vault's CDN is discouraged and can get the feed disabled.
 *  Every photo URL below is rewritten to /api/vault/photo?src=... (proxyPhotoUrl)
 *  so browsers only ever talk to us; the proxy (vaultPhoto.ts) downloads +
 *  caches to disk on first request. See vaultPhoto.ts for the cache + the
 *  host allowlist that keeps the proxy from becoming an open URL fetcher.
 *
 *  The exact property JSON shape is mapped defensively below (fields are read from
 *  several likely locations) because we can't see a live response until the access
 *  token lands. Once it does, verify normaliseListing() against one real item.
 * ============================================================================
 */

// Read env lazily (inside functions), not at module load: vault.ts is imported
// before anything runs dotenv.config(), so top-level reads would see empty vars.
const DEFAULT_BASE_URL = "https://ap-southeast-2.api.vaultre.com.au/api/v1.3";
const baseUrl = () => (process.env.VAULT_API_BASE_URL || DEFAULT_BASE_URL).replace(/\/$/, "");
const apiKey = () => process.env.VAULT_API_KEY ?? "";
const accessToken = () => process.env.VAULT_ACCESS_TOKEN ?? "";

const CACHE_TTL_MS = 10 * 60 * 1000; // 10 minutes
const PAGE_SIZE = 50;
const MAX_PAGES = 10; // safety cap (≤500 listings) so a bad response can't loop forever

/** The clean, site-facing listing shape the front-end renders. */
export interface VaultListing {
  id: string;
  address: string;
  suburb: string;
  state: string;
  postcode: string;
  price: string; // display string, e.g. "$1,250,000" or "Contact Agent"
  bedrooms: number;
  bathrooms: number;
  parking: number;
  propertyType: string;
  status: "For Sale" | "Sold" | "Under Offer";
  imageUrl: string;
  isPlaceholder: false;
}

/** True only when both credentials are present. Callers fall back to mock otherwise. */
export function vaultConfigured(): boolean {
  return Boolean(apiKey() && accessToken());
}

let cache: { at: number; data: VaultListing[] } | null = null;

/**
 * Returns Manifest's live for-sale listings from Vault RE, normalised and cached.
 * Returns `null` when Vault isn't configured or the API call fails, so the caller
 * can fall back to placeholder data without the page breaking.
 */
export async function getVaultListings(force = false): Promise<VaultListing[] | null> {
  if (!vaultConfigured()) return null;

  if (!force && cache && Date.now() - cache.at < CACHE_TTL_MS) {
    return cache.data;
  }

  try {
    const raw = await fetchAllResidentialForSale();
    const listings = raw.map(normaliseListing).filter((l): l is VaultListing => l !== null);
    cache = { at: Date.now(), data: listings };
    return listings;
  } catch (err) {
    console.error("[vault] fetch failed", err);
    // Serve a slightly-stale cache rather than nothing, if we have one.
    return cache?.data ?? null;
  }
}

async function fetchAllResidentialForSale(): Promise<Record<string, unknown>[]> {
  const all: Record<string, unknown>[] = [];

  for (let page = 1; page <= MAX_PAGES; page++) {
    const url =
      `${baseUrl()}/properties/residential/sale` +
      `?published=true&status=listingOrConditional&pagesize=${PAGE_SIZE}&page=${page}`;

    const res = await fetch(url, {
      method: "GET",
      headers: {
        Accept: "application/json",
        "X-Api-Key": apiKey(),
        Authorization: `Bearer ${accessToken()}`,
      },
    });

    if (!res.ok) {
      throw new Error(`Vault RE ${res.status} on page ${page}: ${await safeText(res)}`);
    }

    const body = (await res.json()) as unknown;
    const { items, totalPages } = unwrapPage(body);
    all.push(...items);

    // Stop when the API reports we're done, or a short page signals the end.
    if (totalPages != null && page >= totalPages) break;
    if (items.length < PAGE_SIZE) break;
  }

  return all;
}

/** Vault paginates as `{ items, totalItems, totalPages, currentPage }`; tolerate a bare array too. */
function unwrapPage(body: unknown): { items: Record<string, unknown>[]; totalPages: number | null } {
  if (Array.isArray(body)) return { items: body as Record<string, unknown>[], totalPages: null };
  if (body && typeof body === "object") {
    const obj = body as Record<string, unknown>;
    const items = Array.isArray(obj.items) ? (obj.items as Record<string, unknown>[]) : [];
    const totalPages = typeof obj.totalPages === "number" ? obj.totalPages : null;
    return { items, totalPages };
  }
  return { items: [], totalPages: null };
}

/* ---- Normalisation --------------------------------------------------------
 * Defensive: reads each field from the most likely location(s) in the Vault
 * property object, falling back gracefully. Verify against a live item once the
 * access token is in place.
 */
function normaliseListing(raw: Record<string, unknown>): VaultListing | null {
  const id = str(raw.id) ?? str(raw.propertyId);
  if (!id) return null;

  const address = (raw.address ?? {}) as Record<string, unknown>;
  const suburbObj = (address.suburb ?? {}) as Record<string, unknown>;
  // State is a nested object { id, name, abbreviation } on the suburb (and on address).
  const stateObj = (suburbObj.state ?? address.state ?? {}) as Record<string, unknown>;

  const suburb = titleCase(str(suburbObj.name) ?? ""); // Vault returns it UPPERCASE
  const state = str(stateObj.abbreviation) ?? str(stateObj.name) ?? "";
  const postcode = str(suburbObj.postcode) ?? "";

  return {
    id,
    address: normaliseStreet(address),
    suburb,
    state,
    postcode,
    price: normalisePrice(raw),
    bedrooms: int(raw.bed) ?? int(raw.bedrooms) ?? 0,
    bathrooms: int(raw.bath) ?? int(raw.bathrooms) ?? 0,
    parking: (int(raw.garages) ?? 0) + (int(raw.carports) ?? 0) + (int(raw.openSpaces) ?? 0) || (int(raw.carSpaces) ?? 0),
    propertyType: normaliseType(raw),
    status: normaliseStatus(raw),
    imageUrl: proxyPhotoUrl(pickPhotoUrl(raw)),
    isPlaceholder: false,
  };
}

/** Build a clean street line from address parts (nicer casing than Vault's UPPERCASE displayAddress). */
function normaliseStreet(address: Record<string, unknown>): string {
  const unit = str(address.unitNumber);
  const streetNumber = str(address.streetNumber);
  const street = str(address.street);
  const number = unit && streetNumber ? `${unit}/${streetNumber}` : (streetNumber ?? unit ?? "");
  const line = [number, street].filter(Boolean).join(" ").trim();
  // Empty street = address withheld by the vendor.
  return line || "Address available on request";
}

/** "KEILOR EAST" → "Keilor East". */
function titleCase(s: string): string {
  return s.toLowerCase().replace(/\b[a-z]/g, (m) => m.toUpperCase());
}

function normalisePrice(raw: Record<string, unknown>): string {
  // POA listings return a clunky "Contact Agent: Address Available On Request" — normalise it.
  if (raw.priceOnApplication === true) return "Contact Agent";
  const life = pickLife(raw);
  const display = str(life.displayPrice) ?? str(raw.displayPrice) ?? str(raw.priceText);
  if (display) return display;
  const numeric = int(life.searchPrice) ?? int(raw.searchPrice) ?? int(raw.price);
  if (numeric && numeric > 0) {
    return numeric.toLocaleString("en-AU", { style: "currency", currency: "AUD", maximumFractionDigits: 0 });
  }
  return "Contact Agent";
}

function normaliseType(raw: Record<string, unknown>): string {
  const t = raw.propertyType ?? raw.type ?? raw.category ?? raw.class;
  if (typeof t === "string") return t;
  if (t && typeof t === "object") return str((t as Record<string, unknown>).name) ?? "Property";
  return "Property";
}

function normaliseStatus(raw: Record<string, unknown>): VaultListing["status"] {
  const s = (str(pickLife(raw).status) ?? str(raw.status) ?? "").toLowerCase();
  if (s.includes("sold")) return "Sold";
  if (s.includes("conditional") || s.includes("offer") || s.includes("under")) return "Under Offer";
  return "For Sale";
}

function pickPhotoUrl(raw: Record<string, unknown>): string {
  const photos = Array.isArray(raw.photos) ? (raw.photos as Record<string, unknown>[]) : [];
  // Prefer the first published photo with a URL; fall back to any photo.
  const pick = photos.find((p) => p.published !== false && str(p.url)) ?? photos.find((p) => str(p.url));
  return (pick && str(pick.url)) ?? str(raw.mainImage) ?? "";
}

/** Rewrite a Vault CDN URL to our self-hosting proxy — browsers never hit Vault directly. */
function proxyPhotoUrl(url: string): string {
  return url ? `/api/vault/photo?src=${encodeURIComponent(url)}` : "";
}

/** The sale-specific fields may sit under a `saleLife`/`life` sub-object. */
function pickLife(raw: Record<string, unknown>): Record<string, unknown> {
  const life = raw.saleLife ?? raw.life ?? raw.saleDetails;
  return life && typeof life === "object" ? (life as Record<string, unknown>) : {};
}

/* ---- small coercion helpers ---- */
function str(v: unknown): string | undefined {
  if (typeof v === "string" && v.trim()) return v.trim();
  if (typeof v === "number") return String(v);
  return undefined;
}
function int(v: unknown): number | undefined {
  const n = typeof v === "string" ? Number(v) : typeof v === "number" ? v : NaN;
  return Number.isFinite(n) ? Math.round(n) : undefined;
}
async function safeText(res: Response): Promise<string> {
  try {
    return (await res.text()).slice(0, 200);
  } catch {
    return "";
  }
}

/* ---- Single-listing detail (for /properties/{id}) -------------------------
 * Same auth + defensive-parsing approach as the list fetch above. Verified
 * against a live response (2026-07-28, property 19492724): description,
 * landArea{value,units} and contactStaff[] all confirmed against the real
 * shape below.
 */
export interface VaultListingDetail extends VaultListing {
  description: string;
  images: string[]; // all published photos, proxied; falls back to [imageUrl]
  landSize: string; // display string, e.g. "650 m²"; empty if unknown
  agentName: string;
  agentPhone: string;
  agentEmail: string;
}

const detailCache = new Map<string, { at: number; data: VaultListingDetail }>();
const DETAIL_CACHE_TTL_MS = 5 * 60 * 1000;

/** Fetch one property's full detail from Vault by id. Null = not configured, not found, or the call failed. */
export async function getVaultListingDetail(id: string): Promise<VaultListingDetail | null> {
  if (!vaultConfigured()) return null;

  const cached = detailCache.get(id);
  if (cached && Date.now() - cached.at < DETAIL_CACHE_TTL_MS) return cached.data;

  try {
    const res = await fetch(`${baseUrl()}/properties/residential/sale/${encodeURIComponent(id)}`, {
      method: "GET",
      headers: {
        Accept: "application/json",
        "X-Api-Key": apiKey(),
        Authorization: `Bearer ${accessToken()}`,
      },
    });

    if (res.status === 404) return null;
    if (!res.ok) throw new Error(`Vault RE ${res.status} on property ${id}: ${await safeText(res)}`);

    const raw = (await res.json()) as Record<string, unknown>;
    const detail = normaliseListingDetail(raw);
    if (detail) detailCache.set(id, { at: Date.now(), data: detail });
    return detail;
  } catch (err) {
    console.error("[vault] detail fetch failed", err);
    // Serve a slightly-stale cache rather than nothing, if we have one.
    return cached?.data ?? null;
  }
}

function normaliseListingDetail(raw: Record<string, unknown>): VaultListingDetail | null {
  const base = normaliseListing(raw);
  if (!base) return null;

  const description =
    str(raw.description) ?? str(raw.marketingText) ?? str(raw.webRemarks) ?? str(raw.headline) ?? "";

  const photos = Array.isArray(raw.photos) ? (raw.photos as Record<string, unknown>[]) : [];
  const images = photos
    .filter((p) => p.published !== false && str(p.url))
    .map((p) => proxyPhotoUrl(str(p.url)!));
  if (images.length === 0 && base.imageUrl) images.push(base.imageUrl);

  // Verified against a live response (2026-07-28): { value, units } — e.g. { value: 5, units: "acre" }.
  const land = (raw.landArea ?? {}) as Record<string, unknown>;
  const landValue = int(land.value);
  const landUnit = str(land.units) ?? "m²";
  const landSize = landValue ? `${landValue.toLocaleString()} ${landUnit}` : "";

  // Verified against a live response (2026-07-28): raw.contactStaff[], each with
  // firstName/lastName/email/phoneNumbers[{number,typeCode}] (not a flat "phone").
  const staff = Array.isArray(raw.contactStaff) ? (raw.contactStaff as Record<string, unknown>[]) : [];
  const agent = staff[0] ?? {};
  const agentName = [str(agent.firstName), str(agent.lastName)].filter(Boolean).join(" ");
  const phones = Array.isArray(agent.phoneNumbers) ? (agent.phoneNumbers as Record<string, unknown>[]) : [];
  const mobile = phones.find((p) => p.typeCode === "M") ?? phones[0];

  return {
    ...base,
    description,
    images,
    landSize,
    agentName,
    agentPhone: str(mobile?.number) ?? "",
    agentEmail: str(agent.email) ?? "",
  };
}
